name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          preCommands: pnpm build
          command: wrangler deploy adapter/cloudflare.ts --name spotify-mobile-lyrics-api
          packageManager: pnpm
          secrets: |
            SP_DC
        env:
          SP_DC: ${{ secrets.SP_DC }}
